### PR TITLE
Changing the URL user id number in admin accounting table now refresh the table

### LINKED ISSUE #441: Changing the URL user id number in admin accounting table does not refresh the table
To reproduce: 

- Open the Accounting dialog for a given user.
- modify the url in the top bar
- the title will change the user id, but the table will not be updated.

### PR DESCRIPTION
**Pull request by martinRenou**
The Vue component now listens to changes of id and update the table.

Closes #441

### CODE REVIEW

**Comment by stefanoborini** [comment]
Write some selenium test.

File: frontend/admin/vue-components/AccountingView.vue [hunk 1]
```diff
@@ -124,6 +124,12 @@
           this.communicationError = "The request could not be executed successfully";
         });
       }
+    },
+
+    watch: {
+      '$route.params.id': function() {
```
Comment (stefanoborini) [inline frontend/admin/vue-components/AccountingView.vue]: clearTable();
updateTable();

File: frontend/admin/vue-components/AccountingView.vue [hunk 2]
```diff
@@ -78,9 +78,9 @@
     methods: {
       updateTable: function() {
         this.communicationError = null;
+        this.table.rows = [];
         resources.Accounting.items({filter: JSON.stringify({user_id: this.$route.params.id })})
         .done((identifiers, items) => {
-          this.table.rows = [];
```
Comment (stefanoborini) [inline frontend/admin/vue-components/AccountingView.vue]: leave it here.
